name: "Release"
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  sign:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: extension

      - name: "web-ext sign"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: unlisted
          apiKey: ${{ secrets.AMO_SIGN_KEY }}
          apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
          timeout: 900000

      - name: "Rename xpi"
        id: rename-xpi
        run: mv ${{ steps.web-ext-sign.outputs.target }} itvx-adblocker-firefox-${{ github.ref_name }}.xpi

      - name: "Zip /extension"
        id: zip-extension
        run: git archive -o web-ext-artifacts/itv-adblocker-chrome-${{ github.ref_name }}.zip HEAD:extension

      - name: "Create Release"
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            itvx-adblocker-firefox-${{ github.ref_name }}.xpi
            itvx-adblocker-chrome-${{ github.ref_name }}.zip
